<a href="https://colab.research.google.com/github/cristiancamiloosoriohernandez/Taller-4---Consumo-de-API-Power-BI/blob/main/Consumo_de_API_%2B_Powr_BI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CONSULTA DE API

### 1. Importar la librería y definir la URL de la API

Usaremos la librería `requests`. Si deseas consultar una API que requiere autenticación o parámetros, puedes incluirlos en la consulta. En este ejemplo, usaremos una API pública gratuita que devuelve datos de usuarios de prueba.

In [32]:
import requests

# URL de la API de datos.gov.co proporcionada
url = 'https://www.datos.gov.co/api/v3/views/68pj-ac7b/query.json?query=SELECT%20departamento%2C%20ciudad%2C%20placa_vehiculo%2C%20fecha%2C%20codigo_infraccion%20ORDER%20BY%20fecha%20DESC'

# Realizar la petición GET
respuesta = requests.get(url)

### 2. Verificar el estado y mostrar los resultados

Es importante verificar si la petición fue exitosa (código de estado `200`) antes de procesar los datos.

In [33]:
if respuesta.status_code == 200:
    # Convertir la respuesta a formato JSON
    datos = respuesta.json()
    print("¡Consulta exitosa a datos.gov.co!")
    # Mostramos los primeros 5 elementos para no saturar la pantalla si son muchos datos
    display(datos[:5] if isinstance(datos, list) else datos)
else:
    print(f"Error al consultar la API. Código de estado: {respuesta.status_code}")
    print(respuesta.text)

¡Consulta exitosa a datos.gov.co!

[{'departamento': 'META',
  'ciudad': 'VILLAVICENCIO',
  'placa_vehiculo': 'UBW991',
  'fecha': '9/12/2021 9:59:00 a. m.',
  'codigo_infraccion': 'C03',
  ':id': 'row-atvs.8hgu.vivy',
  ':version': 'rv-e6hb_tgj8~fwka',
  ':created_at': '2025-02-18T14:59:57.722Z',
  ':updated_at': '2025-02-18T14:59:57.722Z'},
 {'departamento': 'CALDAS',
  'ciudad': 'MANIZALES',
  'placa_vehiculo': 'NAH651',
  'fecha': '9/12/2021 9:56:00 a. m.',
  'codigo_infraccion': 'C35',
  ':id': 'row-dffx~grg2.v588',
  ':version': 'rv-r5sa_ij7v_gfsb',
  ':created_at': '2025-02-18T14:59:57.722Z',
  ':updated_at': '2025-02-18T14:59:57.722Z'},
 {'departamento': 'NORTE DE SANTANDER',
  'ciudad': 'CUCUTA',
  'fecha': '9/12/2021 9:56:00 a. m.',
  'codigo_infraccion': 'D01',
  ':id': 'row-8cs8.rbye.3k79',
  ':version': 'rv-3gz6~xf5j~tkq4',
  ':created_at': '2025-02-18T14:59:57.722Z',
  ':updated_at': '2025-02-18T14:59:57.722Z'},
 {'departamento': 'CALDAS',
  'ciudad': 'CHINCHINA',
  'placa_vehiculo': 'HVT31C',
  'fecha': '9/12/2021 9:50:00 p. m.',
  'codigo_infraccion': 'D01',
  ':id': 'row-3u9z_4et4_asdk',
  ':version': 'rv-dcz9-cmf6.rbpb',
  ':created_at': '2025-02-18T14:59:57.722Z',
  ':updated_at': '2025-02-18T14:59:57.722Z'},
 {'departamento': 'BOLIVAR',
  'ciudad': 'CARTAGENA',
  'placa_vehiculo': 'FUP162',
  'fecha': '9/12/2021 9:50:00 a. m.',
  'codigo_infraccion': 'C02',
  ':id': 'row-2hkk~uk8m.2jv2',
  ':version': 'rv-t9v4_tc7c-786i',
  ':created_at': '2025-02-18T14:59:57.722Z',
  ':updated_at': '2025-02-18T14:59:57.722Z'}]

In [34]:
import pandas as pd

df = pd.DataFrame(datos)
df.head()

,departamento,ciudad,placa_vehiculo,fecha,codigo_infraccion,:id,:version,:created_at,:updated_at
0,META,VILLAVICENCIO,UBW991,9/12/2021 9:59:00 a. m.,C03,row-atvs.8hgu.vivy,rv-e6hb_tgj8~fwka,2025-02-18T14:59:57.722Z,2025-02-18T14:59:57.722Z
1,CALDAS,MANIZALES,NAH651,9/12/2021 9:56:00 a. m.,C35,row-dffx~grg2.v588,rv-r5sa_ij7v_gfsb,2025-02-18T14:59:57.722Z,2025-02-18T14:59:57.722Z
2,NORTE DE SANTANDER,CUCUTA,NaN,9/12/2021 9:56:00 a. m.,D01,row-8cs8.rbye.3k79,rv-3gz6~xf5j~tkq4,2025-02-18T14:59:57.722Z,2025-02-18T14:59:57.722Z
3,CALDAS,CHINCHINA,HVT31C,9/12/2021 9:50:00 p. m.,D01,row-3u9z_4et4_asdk,rv-dcz9-cmf6.rbpb,2025-02-18T14:59:57.722Z,2025-02-18T14:59:57.722Z
4,BOLIVAR,CARTAGENA,FUP162,9/12/2021 9:50:00 a. m.,C02,row-2hkk~uk8m.2jv2,rv-t9v4_tc7c-786i,2025-02-18T14:59:57.722Z,2025-02-18T14:59:57.722Z

# EXPLORACIÓN Y TRANSFORMACIÓN DE DATOS

### 1. Identificar los tipos de datos y definir la dirección de la busqueda

Usaremos la libreria de acceso publico del SIMIT para presentar la comparación entre ciudades, diás, tipo de infraccion y tipo de vehiculo.

In [72]:
# Depurar columnas de la tabla
tabla = df[["departamento", "ciudad", "placa_vehiculo", "fecha", "codigo_infraccion"]].copy()
tabla.head()

,departamento,ciudad,placa_vehiculo,fecha,codigo_infraccion
0,META,VILLAVICENCIO,UBW991,9/12/2021 9:59:00 a. m.,C03
1,CALDAS,MANIZALES,NAH651,9/12/2021 9:56:00 a. m.,C35
2,NORTE DE SANTANDER,CUCUTA,NaN,9/12/2021 9:56:00 a. m.,D01
3,CALDAS,CHINCHINA,HVT31C,9/12/2021 9:50:00 p. m.,D01
4,BOLIVAR,CARTAGENA,FUP162,9/12/2021 9:50:00 a. m.,C02

In [74]:
# Entender datos de la tabla
tabla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1476471 entries, 0 to 1476470
Data columns (total 5 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   departamento       1476471 non-null  object
 1   ciudad             1476471 non-null  object
 2   placa_vehiculo     1466879 non-null  object
 3   fecha              1476471 non-null  object
 4   codigo_infraccion  1476471 non-null  object
dtypes: object(5)
memory usage: 56.3+ MB

### 2. Transformar datos

Empezaremos a dar manejo a los datos para limpiar y mejorar la legibilidad del conjunto.

In [75]:
# Reemplazar datos nulos de placa_vehiculo
# El total de datos nulos representa un tipo de infracción impuesto al conductor, mal/no digitado o no identificada, en cualquier caso la multa se asocia a la cedula, por ende se reeemplazaran por "conductor".

tabla["placa_vehiculo"] = tabla["placa_vehiculo"].fillna("Conductor")
tabla.head()

,departamento,ciudad,placa_vehiculo,fecha,codigo_infraccion
0,META,VILLAVICENCIO,UBW991,9/12/2021 9:59:00 a. m.,C03
1,CALDAS,MANIZALES,NAH651,9/12/2021 9:56:00 a. m.,C35
2,NORTE DE SANTANDER,CUCUTA,Conductor,9/12/2021 9:56:00 a. m.,D01
3,CALDAS,CHINCHINA,HVT31C,9/12/2021 9:50:00 p. m.,D01
4,BOLIVAR,CARTAGENA,FUP162,9/12/2021 9:50:00 a. m.,C02

In [76]:
# Verificar los tipos de datos

tabla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1476471 entries, 0 to 1476470
Data columns (total 5 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   departamento       1476471 non-null  object
 1   ciudad             1476471 non-null  object
 2   placa_vehiculo     1476471 non-null  object
 3   fecha              1476471 non-null  object
 4   codigo_infraccion  1476471 non-null  object
dtypes: object(5)
memory usage: 56.3+ MB

In [77]:
# Conteo de duplicados

tabla.duplicated().sum()

np.int64(7624)

In [78]:
# Mostrar todas las filas con almenos un duplicado

tabla[tabla.duplicated(keep=False)]

,departamento,ciudad,placa_vehiculo,fecha,codigo_infraccion
241,CUNDINAMARCA,CAJICA - DEPT CUNDINAMARCA,GZX28D,9/12/2021 6:27:00 p. m.,H02
242,CUNDINAMARCA,CAJICA - DEPT CUNDINAMARCA,GZX28D,9/12/2021 6:27:00 p. m.,H02
479,BOLIVAR,CARTAGENA,MMZ703,9/12/2021 3:20:00 p. m.,H02
480,BOLIVAR,CARTAGENA,MMZ703,9/12/2021 3:20:00 p. m.,H02
571,ANTIOQUIA,ENVIGADO,SNW544,9/12/2021 12:36:00 p. m.,D01
...,...,...,...,...,...
1476067,CALDAS,MANIZALES,SIN,01/01/2024,H10
1476152,CALDAS,MANIZALES,SIN,01/01/2024,H10
1476153,CALDAS,MANIZALES,SIN,01/01/2024,H10
1476284,ANTIOQUIA,NECOCLI,BVL13D,01/01/2023,D02
1476469,ANTIOQUIA,NECOCLI,BVL13D,01/01/2023,D02

In [79]:
# Eliminación de dupicados

tabla.drop_duplicates(inplace=True, keep="first")
tabla.duplicated().sum()

np.int64(0)

In [80]:
# reseteo de index

tabla = tabla.reset_index(drop=True)
tabla.head()

,departamento,ciudad,placa_vehiculo,fecha,codigo_infraccion
0,META,VILLAVICENCIO,UBW991,9/12/2021 9:59:00 a. m.,C03
1,CALDAS,MANIZALES,NAH651,9/12/2021 9:56:00 a. m.,C35
2,NORTE DE SANTANDER,CUCUTA,Conductor,9/12/2021 9:56:00 a. m.,D01
3,CALDAS,CHINCHINA,HVT31C,9/12/2021 9:50:00 p. m.,D01
4,BOLIVAR,CARTAGENA,FUP162,9/12/2021 9:50:00 a. m.,C02

In [81]:
# Identifiar valores unicos dentro da las columnas

sorted(tabla["departamento"].unique())

['AMAZONAS',
 'ANTIOQUIA',
 'ARAUCA',
 'ATLANTICO',
 'BOGOTA D.C.',
 'BOLIVAR',
 'BOYACA',
 'CALDAS',
 'CAQUETA',
 'CASANARE',
 'CAUCA',
 'CESAR',
 'CHOCO',
 'CORDOBA',
 'CUNDINAMARCA',
 'GUAINIA',
 'GUAVIARE',
 'HUILA',
 'LA GUAJIRA',
 'MAGDALENA',
 'META',
 'NARINO',
 'NORTE DE SANTANDER',
 'PUTUMAYO',
 'QUINDIO',
 'RISARALDA',
 'SAN ANDRES Y PROVIDENCIA',
 'SANTANDER',
 'SUCRE',
 'TOLIMA',
 'VALLE DEL CAUCA']

In [82]:
sorted(tabla["ciudad"].unique())

['ABEJORRAL',
 'ACACIAS',
 'AGUACHICA',
 'AGUADAS',
 'AGUAZUL',
 'AGUAZUL - DPTAL CASANARE',
 'AGUSTIN CODAZZI',
 'ALBANIA',
 'ALCALA',
 'ALCALA - DEPT VALLE',
 'ALVARADO',
 'AMAGA',
 'AMALFI',
 'ANDALUCIA',
 'ANDES',
 'ANGOSTURA',
 'ANORI',
 'ANSERMA',
 'ANSERMANUEVO',
 'ANSERMANUEVO - DEPT VALLE',
 'ANT-DAG',
 'ANTIOQUIA',
 'APARTADO',
 'ARACATACA',
 'ARANZAZU',
 'ARATOCA',
 'ARAUCA',
 'ARAUQUITA',
 'ARBELAEZ',
 'ARBELAEZ - DPTAL CUNDINAMARCA',
 'ARGELIA',
 'ARJONA',
 'ARMENIA',
 'ARMERO - GUAYABAL',
 'ATLANTICO',
 'BARBOSA',
 'BARBOSA (SANT)',
 'BARICHARA',
 'BARRANCABERMEJA',
 'BARRANQUILLA',
 'BELEN ANDAQUIES',
 'BELEN DE LOS ANDAQUIES',
 'BELLO',
 'BOGOTA D.C.',
 'BOLIVAR',
 'BOLIVAR - DEPT VALLE',
 'BOSCONIA',
 'BUCARAMANGA',
 'BUENAVENTURA',
 'BUGA',
 'BUGALAGRANDE',
 'BUGALAGRANDE - DEPT VALLE',
 'CA?ASGORDAS',
 'CACERES',
 'CAICEDONIA',
 'CAJIBIO',
 'CAJICA',
 'CAJICA - DEPT CUNDINAMARCA',
 'CALARCA',
 'CALDAS',
 'CALDAS (ANT)',
 'CALDONO',
 'CALI',
 'CALOTO',
 'CANASGORDAS',
 'CANDELARIA',
 'CAQUEZA',
 'CARAMANTA',
 'CAREPA',
 'CARMEN DE BOLIVAR',
 'CARMEN DE VIBORAL',
 'CARTAGENA',
 'CARTAGO',
 'CAUCASIA',
 'CERETE',
 'CHACHAGUI',
 'CHAPARRAL',
 'CHARALA',
 'CHIA',
 'CHIGORODO',
 'CHINCHINA',
 'CHINU',
 'CHIPAQUE',
 'CHIPAQUE - DPTAL CUNDINAMARCA',
 'CHIQUINQUIRA',
 'CHOCONTA',
 'CIENAGA',
 'CIMITARRA',
 'CIRCASIA',
 'CIRCASIA (DPTAL)',
 'CISNEROS',
 'CIUDAD BOLIVAR',
 'CLEMENCIA',
 'COCORNA',
 'COMBITA',
 'CONCEPCION',
 'CONCORDIA',
 'COPACABANA',
 'CORDOBA',
 'CORDOBA (DEPT)',
 'COROZAL',
 'COTA',
 'CUCUTA',
 'CURITI',
 'CURUMANI',
 'DAGUA - DEPT VALLE',
 'DEPARTAMENTAL LA GUAJIRA',
 'DEPARTAMENTAL MAGDALENA',
 'DEPARTAMENTAL PUTUMAYO',
 'DEPARTAMENTAL SUCRE',
 'DON MATIAS',
 'DOSQUEBRADAS',
 'DUITAMA',
 'Dagua',
 'EL BAGRE',
 'EL BANCO',
 'EL CARMEN DE BOLIVAR',
 'EL CERRITO',
 'EL PASO',
 'EL PAUJIL',
 'EL PE?OL',
 'EL PLAYON',
 'EL RETIRO',
 'EL ROSAL',
 'EL SANTUARIO',
 'EL ZULIA',
 'ENTRERRIOS',
 'ENVIGADO',
 'ESPINAL',
 'FACATATIVA',
 'FLORENCIA',
 'FLORENCIA_CAQUETA',
 'FLORIDA',
 'FLORIDABLANCA',
 'FONSECA',
 'FRESNO',
 'FRONTINO',
 'FUNDACION',
 'FUNZA',
 'FUSAGASUGA',
 'GALAPA',
 'GARAGOA',
 'GARZON',
 'GINEBRA',
 'GINEBRA (VALLE)',
 'GIRALDO',
 'GIRARDOT',
 'GIRARDOTA',
 'GIRON',
 'GRANADA',
 'GRANADA (META)',
 'GRANADA - ANT',
 'GUACARI',
 'GUADALUPE',
 'GUADUAS',
 'GUAJIRA',
 'GUAMO',
 'GUARNE',
 'GUARNE(DPTAL)',
 'GUATAPE',
 'GUATEQUE',
 'GUAYABAL (ARMERO)',
 'HONDA',
 'HUILA',
 'HUILA (DEPT)',
 'IBAGUE',
 'IPIALES',
 'ISTMINA',
 'ITAG?I',
 'ITAGUI',
 'JAMUNDI',
 'JERICO',
 'LA CALERA',
 'LA CEJA',
 'LA DORADA',
 'LA ESTRELLA',
 'LA HORMIGA',
 'LA JAGUA DE IBIRICO',
 'LA MESA',
 'LA MESA - DEPT CUNDINAMARCA',
 'LA PINTADA',
 'LA PLATA',
 'LA TEBAIDA',
 'LA UNION',
 'LA UNION (ANT)',
 'LA UNION (VALLE)',
 'LA VIRGINIA',
 'LEBRIJA',
 'LETICIA',
 'LIBANO',
 'LORICA',
 'LOS PATIOS',
 'MACEO',
 'MADRID',
 'MAGANGUE',
 'MAGDALENA',
 'MAICAO',
 'MALAGA',
 'MALAMBO',
 'MANIZALES',
 'MANZANARES',
 'MARINILLA',
 'MARIQUITA',
 'MEDELLIN',
 'MELGAR',
 'MERCADERES',
 'META',
 'META (DEPT)',
 'MIRANDA',
 'MOCOA',
 'MOMPOS',
 'MONIQUIRA',
 'MONTERIA',
 'MOSQUERA',
 'NARI?O',
 'NARINO',
 'NECOCLI',
 'NEIRA',
 'NEIVA',
 'NOBSA',
 'OCA?A',
 'OCANA',
 'OIBA',
 'ORITO',
 'ORTEGA',
 'ORTEGA DEPARTAMENTAL',
 'PACHO',
 'PAIPA',
 'PALERMO',
 'PALMIRA',
 'PAMPLONA',
 'PASTO',
 'PATIA (EL BORDO)',
 'PENOL',
 'PEREIRA',
 'PIEDECUESTA',
 'PIENDAMO',
 'PINCHOTE',
 'PITALITO',
 'PLANETA RICA',
 'PLATO',
 'POPAYAN',
 'PRADERA',
 'PUEBLORRICO',
 'PUENTE NACIONAL',
 'PUERTO ASIS',
 'PUERTO BERRIO',
 'PUERTO BOYACA',
 'PUERTO COLOMBIA',
 'PUERTO INIRIDA',
 'PUERTO SALGAR',
 'PUERTO SALGAR - DPTAL CUNDI.',
 'PUERTO TEJADA',
 'PUERTO TRIUNFO',
 'PUPIALES',
 'PURIFICACION',
 'PUTUMAYO',
 'QUIBDO',
 'QUIMBAYA',
 'REMEDIOS',
 'RESTREPO',
 'RETIRO',
 'RICAURTE',
 'RICAURTE - NARI?O',
 'RIOHACHA',
 'RIONEGRO',
 'RIONEGRO (SANT)',
 'RIOSUCIO',
 'ROBLES (LA PAZ)',
 'ROLDANILLO',
 'ROSAS',
 'SABANA DE TORRES',
 'SABANAGRANDE',
 'SABANALARGA',
 'SABANETA',
 'SABOYA',
 'SAHAGUN',
 'SALAMINA',
 'SALGAR',
 'SAMPUES',
 'SAN ANDRES',
 'SAN CARLOS',
 'SAN DIEGO',
 'SAN DIEGO-DPTAL CESAR',
 'SAN GIL',
 'SAN JERONIMO',
 'SAN JERONIMO - DEPT ANTIOQUIA',
 'SAN JOSE DEL GUAVIARE',
 'SAN JUAN DE NEPOMUCENO',
 'SAN LUIS',
 'SAN MARTIN',
 'SAN PEDRO',
 'SAN PEDRO DE LOS MILAGROS',
 'SAN RAFAEL',
 'SAN ROQUE',
 'SAN VICENTE',
 'SAN VICENTE DE CHUCURI',
 'SANTA BARBARA',
 'SANTA CATALINA',
 'SANTA FE DE ANTIOQUIA',
 'SANTA MARTA',
 'SANTA ROSA',
 'SANTA ROSA DE CABAL',
 'SANTA ROSA DE OSOS',
 'SANTA ROSA DE VITERBO',
 'SANTA ROSA DEL SUR',
 'SANTANDER DE QUILICHAO',
 'SANTO DOMINGO',
 'SANTUARIO',
 'SARAVENA',
 'SEC MOVILIDAD DPTAL DE BOLIVAR',
 'SEGOVIA',
 'SEVILLA',
 'SIBATE',
 'SIBATE - DEPT CUNDINAMARCA',
 'SIBUNDOY',
 'SILVANIA',
 'SINCELEJO',
 'SITIONUEVO',
 'SOACHA',
 'SOATA',
 'SOCORRO',
 'SOGAMOSO',
 'SOLEDAD',
 'SONSON',
 'SOPETRAN',
 'SOPO',
 'SUCRE',
 'SUPIA',
 'TAME',
 'TANGUA',
 'TANGUA (DEPT.)',
 'TARAZA',
 'TARSO',
 'TIMBIO',
 'TITIRIBI',
 'TULUA',
 'TUMACO',
 'TUNJA',
 'TUQUERRES',
 'TURBACO',
 'TURBO',
 'UBATE',
 'URRAO',
 'VALDIVIA',
 'VALLEDUPAR',
 'VALPARAISO',
 'VEGACHI',
 'VELEZ',
 'VENECIA',
 'VIJES',
 'VILLA DE LEYVA',
 'VILLA DEL ROSARIO',
 'VILLA RICA',
 'VILLA RICA CAUCA',
 'VILLAGARZON (DPTAL PUTUMAYO)',
 'VILLAMARIA',
 'VILLANUEVA',
 'VILLAVICENCIO',
 'VILLETA',
 'VITERBO',
 'YALI',
 'YARUMAL',
 'YOLOMBO',
 'YONDO',
 'YOPAL',
 'YOTOCO',
 'YUMBO',
 'ZARZAL',
 'ZIPAQUIRA',
 'ZONA BANANERA',
 'ZULIA (DEPT)']

In [83]:
# Reemplazar valores rdundantes y defectuosos

tabla["ciudad"] = tabla["ciudad"].str.strip()
Reemplazos_ciudades = {"AGUAZUL - DPTAL CASANARE":"AGUAZUL",
                       "ALCALA - DEPT VALLE":"ALCALA",
                       "ANSERMANUEVO - DEPT VALLE":"ANSERMANUEVO",
                       "ARBELAEZ - DPTAL CUNDINAMARCA":"ARBELAEZ",
                       "BARBOSA (SANT)":"BARBOSA",
                       "BELEN ANDAQUIES":"BELEN DE LOS ANDAQUIES",
                       "BUGALAGRANDE - DEPT VALLE":"BUGALAGRANDE",
                       "BOLIVAR - DEPT VALLE":"BOLIVAR",
                       "CA?ASGORDAS":"CANASGORDAS",
                       "CAJICA - DEPT CUNDINAMARCA":"CAJICA",
                       "CHIPAQUE - DPTAL CUNDINAMARCA":"CHIPAQUE",
                       "CIRCASIA (DPTAL)":"CIRCASIA",
                       "CORDOBA (DEPT)":"CORDOBA",
                       "DAGUA - DEPT VALLE":"DAGUA",
                       "Dagua":"DAGUA",
                       "DEPARTAMENTAL LA GUAJIRA":"LA GUAJIRA",
                       "DEPARTAMENTAL MAGDALENA":"MAGDALENA",
                       "DEPARTAMENTAL PUTUMAYO":"PUTUMAYO",
                       "DEPARTAMENTAL SUCRE":"SUCRE",
                       "EL CARMEN DE BOLIVAR":"CARMEN DE BOLIVAR",
                       "FLORENCIA_CAQUETA":"FLORENCIA",
                       "CERRITO":"EL CERRITO",
                       "EL PE?OL":"EL PENOL",
                       "PENOL":"EL PENOL",
                       "RETIRO":"EL RETIRO",
                       "ZULIA (DEPT)":"ZULIA",
                       "EL ZULIA":"ZULIA",
                       "SANTUARIO":"EL SANTUARIO",
                       "GINEBRA (VALLE)":"GINEBRA",
                       "GRANADA":"GRANADA (CUND)",
                       "GRANADA - ANT":"GRANADA (ANT)",
                       "GUARNE(DPTAL)":"GUARNE",
                       "ARMERO - GUAYABAL":"ARMERO (GUAYABAL)",
                       "GUAYABAL (ARMERO)":"ARMERO (GUAYABAL)",
                       "HUILA (DEPT)":"HUILA",
                       "ITAG?I":"ITAGUI",
                       "LA MESA - DEPT CUNDINAMARCA":"LA MESA",
                       "LA UNION":"LA UNION (ANT)",
                       "META (DEPT)":"META",
                       "MOMPOS":"MOMPOX",
                       "NARI?O":"NARINO",
                       "OCA?A":"OCANA",
                       "ORTEGA DEPARTAMENTAL":"ORTEGA",
                       "PUERTO SALGAR - DPTAL CUNDI.":"PUERTO SALGAR",
                       "RICAURTE - NARINO":"RICAURTE (NARINO)",
                       "SAN DIEGO-DPTAL CESAR":"SAN DIEGO",
                       "SAN JERONIMO - DEPT ANTIOQUIA":"SAN JERONIMO",
                       "SIBATE - DEPT CUNDINAMARCA":"SIBATE",
                       "TANGUA (DEPT.)":"TANGUA",
                       "VILLA RICA":"VILLA RICA CAUCA",
                       "VILLAGARZON (DPTAL PUTUMAYO)":"VILLAGARZON (PUTUMAYO)",
                       }
tabla["ciudad"] = tabla["ciudad"].replace(Reemplazos_ciudades)
sorted(tabla["ciudad"].unique())

['ABEJORRAL',
 'ACACIAS',
 'AGUACHICA',
 'AGUADAS',
 'AGUAZUL',
 'AGUSTIN CODAZZI',
 'ALBANIA',
 'ALCALA',
 'ALVARADO',
 'AMAGA',
 'AMALFI',
 'ANDALUCIA',
 'ANDES',
 'ANGOSTURA',
 'ANORI',
 'ANSERMA',
 'ANSERMANUEVO',
 'ANT-DAG',
 'ANTIOQUIA',
 'APARTADO',
 'ARACATACA',
 'ARANZAZU',
 'ARATOCA',
 'ARAUCA',
 'ARAUQUITA',
 'ARBELAEZ',
 'ARGELIA',
 'ARJONA',
 'ARMENIA',
 'ARMERO (GUAYABAL)',
 'ATLANTICO',
 'BARBOSA',
 'BARICHARA',
 'BARRANCABERMEJA',
 'BARRANQUILLA',
 'BELEN DE LOS ANDAQUIES',
 'BELLO',
 'BOGOTA D.C.',
 'BOLIVAR',
 'BOSCONIA',
 'BUCARAMANGA',
 'BUENAVENTURA',
 'BUGA',
 'BUGALAGRANDE',
 'CACERES',
 'CAICEDONIA',
 'CAJIBIO',
 'CAJICA',
 'CALARCA',
 'CALDAS',
 'CALDAS (ANT)',
 'CALDONO',
 'CALI',
 'CALOTO',
 'CANASGORDAS',
 'CANDELARIA',
 'CAQUEZA',
 'CARAMANTA',
 'CAREPA',
 'CARMEN DE BOLIVAR',
 'CARMEN DE VIBORAL',
 'CARTAGENA',
 'CARTAGO',
 'CAUCASIA',
 'CERETE',
 'CHACHAGUI',
 'CHAPARRAL',
 'CHARALA',
 'CHIA',
 'CHIGORODO',
 'CHINCHINA',
 'CHINU',
 'CHIPAQUE',
 'CHIQUINQUIRA',
 'CHOCONTA',
 'CIENAGA',
 'CIMITARRA',
 'CIRCASIA',
 'CISNEROS',
 'CIUDAD BOLIVAR',
 'CLEMENCIA',
 'COCORNA',
 'COMBITA',
 'CONCEPCION',
 'CONCORDIA',
 'COPACABANA',
 'CORDOBA',
 'COROZAL',
 'COTA',
 'CUCUTA',
 'CURITI',
 'CURUMANI',
 'DAGUA',
 'DON MATIAS',
 'DOSQUEBRADAS',
 'DUITAMA',
 'EL BAGRE',
 'EL BANCO',
 'EL CERRITO',
 'EL PASO',
 'EL PAUJIL',
 'EL PENOL',
 'EL PLAYON',
 'EL RETIRO',
 'EL ROSAL',
 'EL SANTUARIO',
 'ENTRERRIOS',
 'ENVIGADO',
 'ESPINAL',
 'FACATATIVA',
 'FLORENCIA',
 'FLORIDA',
 'FLORIDABLANCA',
 'FONSECA',
 'FRESNO',
 'FRONTINO',
 'FUNDACION',
 'FUNZA',
 'FUSAGASUGA',
 'GALAPA',
 'GARAGOA',
 'GARZON',
 'GINEBRA',
 'GIRALDO',
 'GIRARDOT',
 'GIRARDOTA',
 'GIRON',
 'GRANADA (ANT)',
 'GRANADA (CUND)',
 'GRANADA (META)',
 'GUACARI',
 'GUADALUPE',
 'GUADUAS',
 'GUAJIRA',
 'GUAMO',
 'GUARNE',
 'GUATAPE',
 'GUATEQUE',
 'HONDA',
 'HUILA',
 'IBAGUE',
 'IPIALES',
 'ISTMINA',
 'ITAGUI',
 'JAMUNDI',
 'JERICO',
 'LA CALERA',
 'LA CEJA',
 'LA DORADA',
 'LA ESTRELLA',
 'LA GUAJIRA',
 'LA HORMIGA',
 'LA JAGUA DE IBIRICO',
 'LA MESA',
 'LA PINTADA',
 'LA PLATA',
 'LA TEBAIDA',
 'LA UNION (ANT)',
 'LA UNION (VALLE)',
 'LA VIRGINIA',
 'LEBRIJA',
 'LETICIA',
 'LIBANO',
 'LORICA',
 'LOS PATIOS',
 'MACEO',
 'MADRID',
 'MAGANGUE',
 'MAGDALENA',
 'MAICAO',
 'MALAGA',
 'MALAMBO',
 'MANIZALES',
 'MANZANARES',
 'MARINILLA',
 'MARIQUITA',
 'MEDELLIN',
 'MELGAR',
 'MERCADERES',
 'META',
 'MIRANDA',
 'MOCOA',
 'MOMPOX',
 'MONIQUIRA',
 'MONTERIA',
 'MOSQUERA',
 'NARINO',
 'NECOCLI',
 'NEIRA',
 'NEIVA',
 'NOBSA',
 'OCANA',
 'OIBA',
 'ORITO',
 'ORTEGA',
 'PACHO',
 'PAIPA',
 'PALERMO',
 'PALMIRA',
 'PAMPLONA',
 'PASTO',
 'PATIA (EL BORDO)',
 'PEREIRA',
 'PIEDECUESTA',
 'PIENDAMO',
 'PINCHOTE',
 'PITALITO',
 'PLANETA RICA',
 'PLATO',
 'POPAYAN',
 'PRADERA',
 'PUEBLORRICO',
 'PUENTE NACIONAL',
 'PUERTO ASIS',
 'PUERTO BERRIO',
 'PUERTO BOYACA',
 'PUERTO COLOMBIA',
 'PUERTO INIRIDA',
 'PUERTO SALGAR',
 'PUERTO TEJADA',
 'PUERTO TRIUNFO',
 'PUPIALES',
 'PURIFICACION',
 'PUTUMAYO',
 'QUIBDO',
 'QUIMBAYA',
 'REMEDIOS',
 'RESTREPO',
 'RICAURTE',
 'RICAURTE - NARI?O',
 'RIOHACHA',
 'RIONEGRO',
 'RIONEGRO (SANT)',
 'RIOSUCIO',
 'ROBLES (LA PAZ)',
 'ROLDANILLO',
 'ROSAS',
 'SABANA DE TORRES',
 'SABANAGRANDE',
 'SABANALARGA',
 'SABANETA',
 'SABOYA',
 'SAHAGUN',
 'SALAMINA',
 'SALGAR',
 'SAMPUES',
 'SAN ANDRES',
 'SAN CARLOS',
 'SAN DIEGO',
 'SAN GIL',
 'SAN JERONIMO',
 'SAN JOSE DEL GUAVIARE',
 'SAN JUAN DE NEPOMUCENO',
 'SAN LUIS',
 'SAN MARTIN',
 'SAN PEDRO',
 'SAN PEDRO DE LOS MILAGROS',
 'SAN RAFAEL',
 'SAN ROQUE',
 'SAN VICENTE',
 'SAN VICENTE DE CHUCURI',
 'SANTA BARBARA',
 'SANTA CATALINA',
 'SANTA FE DE ANTIOQUIA',
 'SANTA MARTA',
 'SANTA ROSA',
 'SANTA ROSA DE CABAL',
 'SANTA ROSA DE OSOS',
 'SANTA ROSA DE VITERBO',
 'SANTA ROSA DEL SUR',
 'SANTANDER DE QUILICHAO',
 'SANTO DOMINGO',
 'SARAVENA',
 'SEC MOVILIDAD DPTAL DE BOLIVAR',
 'SEGOVIA',
 'SEVILLA',
 'SIBATE',
 'SIBUNDOY',
 'SILVANIA',
 'SINCELEJO',
 'SITIONUEVO',
 'SOACHA',
 'SOATA',
 'SOCORRO',
 'SOGAMOSO',
 'SOLEDAD',
 'SONSON',
 'SOPETRAN',
 'SOPO',
 'SUCRE',
 'SUPIA',
 'TAME',
 'TANGUA',
 'TARAZA',
 'TARSO',
 'TIMBIO',
 'TITIRIBI',
 'TULUA',
 'TUMACO',
 'TUNJA',
 'TUQUERRES',
 'TURBACO',
 'TURBO',
 'UBATE',
 'URRAO',
 'VALDIVIA',
 'VALLEDUPAR',
 'VALPARAISO',
 'VEGACHI',
 'VELEZ',
 'VENECIA',
 'VIJES',
 'VILLA DE LEYVA',
 'VILLA DEL ROSARIO',
 'VILLA RICA CAUCA',
 'VILLAGARZON (PUTUMAYO)',
 'VILLAMARIA',
 'VILLANUEVA',
 'VILLAVICENCIO',
 'VILLETA',
 'VITERBO',
 'YALI',
 'YARUMAL',
 'YOLOMBO',
 'YONDO',
 'YOPAL',
 'YOTOCO',
 'YUMBO',
 'ZARZAL',
 'ZIPAQUIRA',
 'ZONA BANANERA',
 'ZULIA']

In [84]:
sorted(tabla["fecha"].unique())

['01/01/2023',
 '01/01/2024',
 '01/02/2023',
 '01/02/2024',
 '01/03/2023',
 '01/03/2024',
 '01/04/2023',
 '01/04/2024',
 '01/05/2023',
 '01/05/2024',
 '01/06/2023',
 '01/06/2024',
 '01/07/2023',
 '01/07/2024',
 '01/08/2022',
 '01/08/2023',
 '01/08/2024',
 '01/09/2022',
 '01/09/2023',
 '01/09/2024',
 '01/10/2022',
 '01/10/2023',
 '01/10/2024',
 '01/11/2022',
 '01/11/2023',
 '01/11/2024',
 '01/12/2022',
 '01/12/2023',
 '01/12/2024',
 '02/01/2023',
 '02/01/2024',
 '02/02/2023',
 '02/02/2024',
 '02/03/2023',
 '02/03/2024',
 '02/04/2023',
 '02/04/2024',
 '02/05/2023',
 '02/05/2024',
 '02/06/2023',
 '02/06/2024',
 '02/07/2023',
 '02/07/2024',
 '02/08/2022',
 '02/08/2023',
 '02/08/2024',
 '02/09/2022',
 '02/09/2023',
 '02/09/2024',
 '02/10/2022',
 '02/10/2023',
 '02/10/2024',
 '02/11/2022',
 '02/11/2023',
 '02/11/2024',
 '02/12/2022',
 '02/12/2023',
 '02/12/2024',
 '03/01/2023',
 '03/01/2024',
 '03/02/2023',
 '03/02/2024',
 '03/03/2023',
 '03/03/2024',
 '03/04/2023',
 '03/04/2024',
 '03/05/2023',
 '03/05/2024',
 '03/06/2023',
 '03/06/2024',
 '03/07/2023',
 '03/07/2024',
 '03/08/2022',
 '03/08/2023',
 '03/08/2024',
 '03/09/2022',
 '03/09/2023',
 '03/09/2024',
 '03/10/2022',
 '03/10/2023',
 '03/10/2024',
 '03/11/2022',
 '03/11/2023',
 '03/11/2024',
 '03/12/2022',
 '03/12/2023',
 '03/12/2024',
 '04/01/2023',
 '04/01/2024',
 '04/02/2023',
 '04/02/2024',
 '04/03/2023',
 '04/03/2024',
 '04/04/2023',
 '04/04/2024',
 '04/05/2023',
 '04/05/2024',
 '04/06/2023',
 '04/06/2024',
 '04/07/2023',
 '04/07/2024',
 '04/08/2022',
 '04/08/2023',
 '04/08/2024',
 '04/09/2022',
 '04/09/2023',
 '04/09/2024',
 '04/10/2022',
 '04/10/2023',
 '04/10/2024',
 '04/11/2022',
 '04/11/2023',
 '04/11/2024',
 '04/12/2022',
 '04/12/2023',
 '04/12/2024',
 '05/01/2023',
 '05/01/2024',
 '05/02/2023',
 '05/02/2024',
 '05/03/2023',
 '05/03/2024',
 '05/04/2023',
 '05/04/2024',
 '05/05/2023',
 '05/05/2024',
 '05/06/2023',
 '05/06/2024',
 '05/07/2023',
 '05/07/2024',
 '05/08/2022',
 '05/08/2023',
 '05/08/2024',
 '05/09/2022',
 '05/09/2023',
 '05/09/2024',
 '05/10/2022',
 '05/10/2023',
 '05/10/2024',
 '05/11/2022',
 '05/11/2023',
 '05/11/2024',
 '05/12/2022',
 '05/12/2023',
 '05/12/2024',
 '06/01/2023',
 '06/01/2024',
 '06/02/2023',
 '06/02/2024',
 '06/03/2023',
 '06/03/2024',
 '06/04/2023',
 '06/04/2024',
 '06/05/2023',
 '06/05/2024',
 '06/06/2023',
 '06/06/2024',
 '06/07/2023',
 '06/07/2024',
 '06/08/2022',
 '06/08/2023',
 '06/08/2024',
 '06/09/2022',
 '06/09/2023',
 '06/09/2024',
 '06/10/2022',
 '06/10/2023',
 '06/10/2024',
 '06/11/2022',
 '06/11/2023',
 '06/11/2024',
 '06/12/2022',
 '06/12/2023',
 '06/12/2024',
 '07/01/2023',
 '07/01/2024',
 '07/02/2023',
 '07/02/2024',
 '07/03/2023',
 '07/03/2024',
 '07/04/2023',
 '07/04/2024',
 '07/05/2023',
 '07/05/2024',
 '07/06/2023',
 '07/06/2024',
 '07/07/2023',
 '07/07/2024',
 '07/08/2022',
 '07/08/2023',
 '07/08/2024',
 '07/09/2022',
 '07/09/2023',
 '07/09/2024',
 '07/10/2022',
 '07/10/2023',
 '07/10/2024',
 '07/11/2022',
 '07/11/2023',
 '07/11/2024',
 '07/12/2022',
 '07/12/2023',
 '07/12/2024',
 '08/01/2023',
 '08/01/2024',
 '08/02/2023',
 '08/02/2024',
 '08/03/2023',
 '08/03/2024',
 '08/04/2023',
 '08/04/2024',
 '08/05/2023',
 '08/05/2024',
 '08/06/2023',
 '08/06/2024',
 '08/07/2023',
 '08/07/2024',
 '08/08/2022',
 '08/08/2023',
 '08/08/2024',
 '08/09/2022',
 '08/09/2023',
 '08/09/2024',
 '08/10/2022',
 '08/10/2023',
 '08/10/2024',
 '08/11/2022',
 '08/11/2023',
 '08/11/2024',
 '08/12/2022',
 '08/12/2023',
 '08/12/2024',
 '09/01/2023',
 '09/01/2024',
 '09/02/2023',
 '09/02/2024',
 '09/03/2023',
 '09/03/2024',
 '09/04/2023',
 '09/04/2024',
 '09/05/2023',
 '09/05/2024',
 '09/06/2023',
 '09/06/2024',
 '09/07/2023',
 '09/07/2024',
 '09/08/2022',
 '09/08/2023',
 '09/08/2024',
 '09/09/2022',
 '09/09/2023',
 '09/09/2024',
 '09/10/2022',
 '09/10/2023',
 '09/10/2024',
 '09/11/2022',
 '09/11/2023',
 '09/11/2024',
 '09/12/2022',
 '09/12/2023',
 '09/12/2024',
 '1/01/2021',
 '1/01/2021 10:00:00 a. m.',
 '1/01/2021 10:00:00 p. m.',
 '1/01/2021 10:03:00 a. m.',
 '1/01/2021 10:03:00 p. m.',
 '1/01/2021 10:04:00 a. m.',
 '1/01/2021 10:05:00 p. m.',
 '1/01/2021 10:09:00 a. m.',
 '1/01/2021 10:10:00 a. m.',
 '1/01/2021 10:11:00 a. m.',
 '1/01/2021 10:13:00 a. m.',
 '1/01/2021 10:14:00 a. m.',
 '1/01/2021 10:16:00 a. m.',
 '1/01/2021 10:20:00 a. m.',
 '1/01/2021 10:20:00 p. m.',
 '1/01/2021 10:30:00 a. m.',
 '1/01/2021 10:30:00 p. m.',
 '1/01/2021 10:40:00 a. m.',
 '1/01/2021 10:40:00 p. m.',
 '1/01/2021 10:50:00 a. m.',
 '1/01/2021 10:50:00 p. m.',
 '1/01/2021 10:53:00 a. m.',
 '1/01/2021 10:57:00 a. m.',
 '1/01/2021 11:00:00 a. m.',
 '1/01/2021 11:00:00 p. m.',
 '1/01/2021 11:01:00 a. m.',
 '1/01/2021 11:04:00 a. m.',
 '1/01/2021 11:10:00 a. m.',
 '1/01/2021 11:10:00 p. m.',
 '1/01/2021 11:14:00 a. m.',
 '1/01/2021 11:20:00 a. m.',
 '1/01/2021 11:20:00 p. m.',
 '1/01/2021 11:26:00 a. m.',
 '1/01/2021 11:30:00 a. m.',
 '1/01/2021 11:30:00 p. m.',
 '1/01/2021 11:31:00 a. m.',
 '1/01/2021 11:33:00 a. m.',
 '1/01/2021 11:34:00 a. m.',
 '1/01/2021 11:35:00 p. m.',
 '1/01/2021 11:40:00 a. m.',
 '1/01/2021 11:45:00 a. m.',
 '1/01/2021 11:47:00 a. m.',
 '1/01/2021 11:49:00 a. m.',
 '1/01/2021 11:50:00 a. m.',
 '1/01/2021 11:50:00 p. m.',
 '1/01/2021 11:52:00 a. m.',
 '1/01/2021 12:00:00 p. m.',
 '1/01/2021 12:01:00 a. m.',
 '1/01/2021 12:01:00 p. m.',
 '1/01/2021 12:05:00 a. m.',
 '1/01/2021 12:09:00 p. m.',
 '1/01/2021 12:10:00 p. m.',
 '1/01/2021 12:19:00 p. m.',
 '1/01/2021 12:20:00 a. m.',
 '1/01/2021 12:20:00 p. m.',
 '1/01/2021 12:24:00 p. m.',
 '1/01/2021 12:30:00 p. m.',
 '1/01/2021 12:32:00 a. m.',
 '1/01/2021 12:32:00 p. m.',
 '1/01/2021 12:40:00 a. m.',
 '1/01/2021 12:40:00 p. m.',
 '1/01/2021 12:41:00 p. m.',
 '1/01/2021 12:43:00 p. m.',
 '1/01/2021 12:50:00 a. m.',
 '1/01/2021 12:50:00 p. m.',
 '1/01/2021 1:00:00 a. m.',
 '1/01/2021 1:00:00 p. m.',
 '1/01/2021 1:01:00 p. m.',
 '1/01/2021 1:02:00 p. m.',
 '1/01/2021 1:04:00 p. m.',
 '1/01/2021 1:05:00 p. m.',
 '1/01/2021 1:10:00 p. m.',
 '1/01/2021 1:13:00 p. m.',
 '1/01/2021 1:20:00 a. m.',
 '1/01/2021 1:20:00 p. m.',
 '1/01/2021 1:30:00 a. m.',
 '1/01/2021 1:30:00 p. m.',
 '1/01/2021 1:38:00 p. m.',
 '1/01/2021 1:40:00 a. m.',
 '1/01/2021 1:41:00 a. m.',
 '1/01/2021 1:50:00 a. m.',
 '1/01/2021 1:50:00 p. m.',
 '1/01/2021 1:57:00 a. m.',
 '1/01/2021 2:00:00 a. m.',
 '1/01/2021 2:03:00 p. m.',
 '1/01/2021 2:10:00 a. m.',
 '1/01/2021 2:11:00 p. m.',
 '1/01/2021 2:12:00 p. m.',
 '1/01/2021 2:20:00 a. m.',
 '1/01/2021 2:20:00 p. m.',
 '1/01/2021 2:30:00 a. m.',
 '1/01/2021 2:30:00 p. m.',
 '1/01/2021 2:40:00 a. m.',
 '1/01/2021 2:40:00 p. m.',
 '1/01/2021 2:50:00 a. m.',
 '1/01/2021 2:50:00 p. m.',
 '1/01/2021 2:59:00 p. m.',
 '1/01/2021 3:00:00 a. m.',
 '1/01/2021 3:00:00 p. m.',
 '1/01/2021 3:10:00 p. m.',
 '1/01/2021 3:18:00 p. m.',
 '1/01/2021 3:20:00 a. m.',
 '1/01/2021 3:20:00 p. m.',
 '1/01/2021 3:24:00 p. m.',
 '1/01/2021 3:30:00 p. m.',
 '1/01/2021 3:32:00 p. m.',
 '1/01/2021 3:33:00 p. m.',
 '1/01/2021 3:40:00 a. m.',
 '1/01/2021 3:40:00 p. m.',
 '1/01/2021 3:41:00 p. m.',
 '1/01/2021 3:42:00 p. m.',
 '1/01/2021 3:50:00 a. m.',
 '1/01/2021 3:50:00 p. m.',
 '1/01/2021 4:00:00 p. m.',
 '1/01/2021 4:01:00 p. m.',
 '1/01/2021 4:04:00 p. m.',
 '1/01/2021 4:05:00 p. m.',
 '1/01/2021 4:10:00 p. m.',
 '1/01/2021 4:12:00 a. m.',
 '1/01/2021 4:16:00 p. m.',
 '1/01/2021 4:20:00 a. m.',
 '1/01/2021 4:20:00 p. m.',
 '1/01/2021 4:26:00 p. m.',
 '1/01/2021 4:27:00 p. m.',
 '1/01/2021 4:30:00 p. m.',
 '1/01/2021 4:32:00 a. m.',
 '1/01/2021 4:40:00 p. m.',
 '1/01/2021 4:50:00 p. m.',
 '1/01/2021 4:51:00 p. m.',
 '1/01/2021 4:56:00 p. m.',
 '1/01/2021 4:59:00 p. m.',
 '1/01/2021 5:00:00 a. m.',
 '1/01/2021 5:00:00 p. m.',
 '1/01/2021 5:01:00 a. m.',
 '1/01/2021 5:08:00 p. m.',
 '1/01/2021 5:10:00 p. m.',
 '1/01/2021 5:12:00 p. m.',
 '1/01/2021 5:16:00 p. m.',
 '1/01/2021 5:18:00 a. m.',
 '1/01/2021 5:18:00 p. m.',
 '1/01/2021 5:20:00 a. m.',
 '1/01/2021 5:20:00 p. m.',
 '1/01/2021 5:21:00 p. m.',
 '1/01/2021 5:23:00 p. m.',
 '1/01/2021 5:25:00 p. m.',
 '1/01/2021 5:29:00 p. m.',
 '1/01/2021 5:30:00 p. m.',
 '1/01/2021 5:31:00 p. m.',
 '1/01/2021 5:32:00 p. m.',
 '1/01/2021 5:34:00 p. m.',
 '1/01/2021 5:35:00 p. m.',
 '1/01/2021 5:40:00 p. m.',
 '1/01/2021 5:42:00 p. m.',
 '1/01/2021 5:45:00 p. m.',
 '1/01/2021 5:47:00 p. m.',
 '1/01/2021 5:50:00 p. m.',
 '1/01/2021 5:51:00 p. m.',
 '1/01/2021 5:57:00 p. m.',
 '1/01/2021 6:00:00 a. m.',
 '1/01/2021 6:00:00 p. m.',
 '1/01/2021 6:01:00 p. m.',
 '1/01/2021 6:02:00 p. m.',
 '1/01/2021 6:04:00 p. m.',
 '1/01/2021 6:06:00 p. m.',
 '1/01/2021 6:09:00 p. m.',
 '1/01/2021 6:10:00 p. m.',
 '1/01/2021 6:11:00 p. m.',
 '1/01/2021 6:14:00 p. m.',
 '1/01/2021 6:16:00 p. m.',
 '1/01/2021 6:18:00 a. m.',
 '1/01/2021 6:18:00 p. m.',
 '1/01/2021 6:20:00 p. m.',
 '1/01/2021 6:28:00 p. m.',
 '1/01/2021 6:30:00 p. m.',
 '1/01/2021 6:34:00 p. m.',
 '1/01/2021 6:35:00 a. m.',
 '1/01/2021 6:40:00 a. m.',
 '1/01/2021 6:40:00 p. m.',
 '1/01/2021 6:45:00 p. m.',
 '1/01/2021 6:46:00 p. m.',
 '1/01/2021 6:48:00 p. m.',
 '1/01/2021 6:50:00 a. m.',
 '1/01/2021 6:50:00 p. m.',
 '1/01/2021 6:56:00 p. m.',
 '1/01/2021 7:00:00 a. m.',
 '1/01/2021 7:00:00 p. m.',
 '1/01/2021 7:05:00 p. m.',
 '1/01/2021 7:10:00 p. m.',
 '1/01/2021 7:12:00 p. m.',
 '1/01/2021 7:16:00 p. m.',
 '1/01/2021 7:18:00 p. m.',
 '1/01/2021 7:19:00 p. m.',
 '1/01/2021 7:20:00 a. m.',
 '1/01/2021 7:25:00 p. m.',
 '1/01/2021 7:26:00 p. m.',
 '1/01/2021 7:30:00 a. m.',
 '1/01/2021 7:30:00 p. m.',
 '1/01/2021 7:49:00 p. m.',
 '1/01/2021 7:50:00 a. m.',
 '1/01/2021 7:52:00 p. m.',
 '1/01/2021 7:59:00 p. m.',
 '1/01/2021 8:00:00 a. m.',
 '1/01/2021 8:00:00 p. m.',
 '1/01/2021 8:01:00 a. m.',
 '1/01/2021 8:10:00 a. m.',
 '1/01/2021 8:10:00 p. m.',
 '1/01/2021 8:20:00 a. m.',
 '1/01/2021 8:27:00 a. m.',
 '1/01/2021 8:30:00 a. m.',
 '1/01/2021 8:30:00 p. m.',
 '1/01/2021 8:40:00 a. m.',
 '1/01/2021 8:40:00 p. m.',
 '1/01/2021 8:50:00 a. m.',
 '1/01/2021 9:00:00 a. m.',
 '1/01/2021 9:10:00 a. m.',
 '1/01/2021 9:10:00 p. m.',
 '1/01/2021 9:20:00 a. m.',
 '1/01/2021 9:30:00 a. m.',
 '1/01/2021 9:30:00 p. m.',
 '1/01/2021 9:33:00 a. m.',
 '1/01/2021 9:36:00 a. m.',
 '1/01/2021 9:38:00 a. m.',
 '1/01/2021 9:40:00 a. m.',
 '1/01/2021 9:43:00 a. m.',
 '1/01/2021 9:47:00 a. m.',
 '1/01/2021 9:50:00 a. m.',
 '1/01/2021 9:50:00 p. m.',
 '1/01/2021 9:51:00 a. m.',
 '1/01/2021 9:54:00 p. m.',
 '1/01/2022',
 '1/01/2022 10:00:00 a. m.',
 '1/01/2022 10:00:00 p. m.',
 '1/01/2022 10:05:00 a. m.',
 '1/01/2022 10:06:00 a. m.',
 '1/01/2022 10:10:00 a. m.',
 '1/01/2022 10:15:00 a. m.',
 '1/01/2022 10:15:00 p. m.',
 '1/01/2022 10:16:00 p. m.',
 '1/01/2022 10:17:00 a. m.',
 '1/01/2022 10:20:00 a. m.',
 '1/01/2022 10:20:00 p. m.',
 '1/01/2022 10:22:00 a. m.',
 '1/01/2022 10:23:00 p. m.',
 '1/01/2022 10:26:00 a. m.',
 '1/01/2022 10:28:00 a. m.',
 '1/01/2022 10:29:00 a. m.',
 '1/01/2022 10:30:00 a. m.',
 '1/01/2022 10:30:00 p. m.',
 '1/01/2022 10:33:00 p. m.',
 '1/01/2022 10:40:00 a. m.',
 '1/01/2022 10:42:00 a. m.',
 '1/01/2022 10:45:00 a. m.',
 '1/01/2022 10:46:00 p. m.',
 '1/01/2022 10:50:00 a. m.',
 '1/01/2022 10:50:00 p. m.',
 '1/01/2022 10:52:00 a. m.',
 '1/01/2022 10:54:00 a. m.',
 '1/01/2022 11:00:00 a. m.',
 '1/01/2022 11:00:00 p. m.',
 '1/01/2022 11:01:00 a. m.',
 '1/01/2022 11:01:00 p. m.',
 '1/01/2022 11:02:00 a. m.',
 '1/01/2022 11:03:00 p. m.',
 '1/01/2022 11:06:00 p. m.',
 '1/01/2022 11:10:00 a. m.',
 '1/01/2022 11:10:00 p. m.',
 '1/01/2022 11:11:00 p. m.',
 '1/01/2022 11:13:00 a. m.',
 '1/01/2022 11:15:00 p. m.',
 '1/01/2022 11:17:00 a. m.',
 '1/01/2022 11:20:00 a. m.',
 '1/01/2022 11:20:00 p. m.',
 '1/01/2022 11:23:00 a. m.',
 '1/01/2022 11:24:00 p. m.',
 '1/01/2022 11:25:00 a. m.',
 '1/01/2022 11:25:00 p. m.',
 '1/01/2022 11:26:00 a. m.',
 '1/01/2022 11:30:00 a. m.',
 '1/01/2022 11:30:00 p. m.',
 '1/01/2022 11:31:00 a. m.',
 '1/01/2022 11:32:00 a. m.',
 '1/01/2022 11:33:00 a. m.',
 '1/01/2022 11:34:00 a. m.',
 '1/01/2022 11:36:00 a. m.',
 '1/01/2022 11:38:00 a. m.',
 '1/01/2022 11:40:00 a. m.',
 '1/01/2022 11:43:00 a. m.',
 '1/01/2022 11:44:00 a. m.',
 '1/01/2022 11:49:00 p. m.',
 '1/01/2022 11:50:00 a. m.',
 '1/01/2022 11:53:00 a. m.',
 '1/01/2022 11:59:00 a. m.',
 '1/01/2022 12:00:00 p. m.',
 '1/01/2022 12:09:00 p. m.',
 '1/01/2022 12:10:00 a. m.',
 '1/01/2022 12:10:00 p. m.',
 '1/01/2022 12:11:00 p. m.',
 '1/01/2022 12:20:00 a. m.',
 '1/01/2022 12:20:00 p. m.',
 '1/01/2022 12:29:00 p. m.',
 '1/01/2022 12:30:00 a. m.',
 '1/01/2022 12:30:00 p. m.',
 '1/01/2022 12:35:00 a. m.',
 '1/01/2022 12:40:00 a. m.',
 '1/01/2022 12:40:00 p. m.',
 '1/01/2022 12:41:00 a. m.',
 '1/01/2022 12:42:00 a. m.',
 '1/01/2022 12:50:00 a. m.',
 '1/01/2022 12:50:00 p. m.',
 '1/01/2022 1:00:00 a. m.',
 '1/01/2022 1:00:00 p. m.',
 '1/01/2022 1:03:00 p. m.',
 '1/01/2022 1:10:00 a. m.',
 '1/01/2022 1:10:00 p. m.',
 '1/01/2022 1:15:00 a. m.',
 '1/01/2022 1:20:00 a. m.',
 '1/01/2022 1:21:00 p. m.',
 '1/01/2022 1:24:00 p. m.',
 '1/01/2022 1:30:00 a. m.',
 '1/01/2022 1:30:00 p. m.',
 '1/01/2022 1:31:00 p. m.',
 '1/01/2022 1:33:00 a. m.',
 '1/01/2022 1:35:00 p. m.',
 '1/01/2022 1:37:00 a. m.',
 '1/01/2022 1:40:00 p. m.',
 '1/01/2022 1:42:00 a. m.',
 '1/01/2022 1:44:00 p. m.',
 '1/01/2022 1:46:00 a. m.',
 '1/01/2022 1:49:00 a. m.',
 '1/01/2022 1:50:00 p. m.',
 '1/01/2022 1:51:00 a. m.',
 '1/01/2022 1:56:00 p. m.',
 '1/01/2022 1:58:00 a. m.',
 '1/01/2022 2:00:00 p. m.',
 '1/01/2022 2:01:00 a. m.',
 '1/01/2022 2:07:00 a. m.',
 '1/01/2022 2:09:00 a. m.',
 '1/01/2022 2:10:00 p. m.',
 '1/01/2022 2:15:00 a. m.',
 '1/01/2022 2:20:00 p. m.',
 '1/01/2022 2:21:00 a. m.',
 '1/01/2022 2:21:00 p. m.',
 '1/01/2022 2:26:00 a. m.',
 '1/01/2022 2:27:00 a. m.',
 '1/01/2022 2:30:00 a. m.',
 '1/01/2022 2:30:00 p. m.',
 '1/01/2022 2:32:00 p. m.',
 '1/01/2022 2:35:00 p. m.',
 '1/01/2022 2:40:00 p. m.',
 '1/01/2022 2:43:00 p. m.',
 '1/01/2022 2:45:00 a. m.',
 '1/01/2022 2:49:00 p. m.',
 '1/01/2022 2:50:00 a. m.',
 '1/01/2022 2:50:00 p. m.',
 '1/01/2022 2:51:00 p. m.',
 '1/01/2022 2:54:00 p. m.',
 '1/01/2022 2:55:00 p. m.',
 '1/01/2022 2:57:00 p. m.',
 '1/01/2022 2:59:00 p. m.',
 '1/01/2022 3:00:00 a. m.',
 '1/01/2022 3:00:00 p. m.',
 '1/01/2022 3:04:00 p. m.',
 '1/01/2022 3:07:00 p. m.',
 '1/01/2022 3:08:00 p. m.',
 '1/01/2022 3:09:00 a. m.',
 '1/01/2022 3:10:00 a. m.',
 '1/01/2022 3:10:00 p. m.',
 '1/01/2022 3:12:00 p. m.',
 '1/01/2022 3:16:00 a. m.',
 '1/01/2022 3:20:00 a. m.',
 '1/01/2022 3:20:00 p. m.',
 '1/01/2022 3:24:00 a. m.',
 '1/01/2022 3:24:00 p. m.',
 '1/01/2022 3:30:00 p. m.',
 '1/01/2022 3:34:00 p. m.',
 '1/01/2022 3:36:00 a. m.',
 '1/01/2022 3:39:00 p. m.',
 '1/01/2022 3:40:00 p. m.',
 '1/01/2022 3:41:00 p. m.',
 '1/01/2022 3:43:00 p. m.',
 '1/01/2022 3:50:00 p. m.',
 '1/01/2022 4:00:00 p. m.',
 '1/01/2022 4:03:00 p. m.',
 '1/01/2022 4:10:00 p. m.',
 '1/01/2022 4:12:00 p. m.',
 '1/01/2022 4:13:00 p. m.',
 '1/01/2022 4:20:00 a. m.',
 '1/01/2022 4:20:00 p. m.',
 '1/01/2022 4:22:00 p. m.',
 '1/01/2022 4:25:00 p. m.',
 '1/01/2022 4:30:00 a. m.',
 '1/01/2022 4:30:00 p. m.',
 '1/01/2022 4:31:00 p. m.',
 '1/01/2022 4:33:00 p. m.',
 '1/01/2022 4:37:00 p. m.',
 '1/01/2022 4:40:00 a. m.',
 '1/01/2022 4:40:00 p. m.',
 '1/01/2022 4:42:00 a. m.',
 '1/01/2022 4:42:00 p. m.',
 '1/01/2022 4:49:00 p. m.',
 '1/01/2022 4:50:00 a. m.',
 '1/01/2022 4:50:00 p. m.',
 '1/01/2022 4:52:00 a. m.',
 '1/01/2022 4:53:00 p. m.',
 '1/01/2022 5:00:00 a. m.',
 '1/01/2022 5:00:00 p. m.',
 '1/01/2022 5:03:00 a. m.',
 '1/01/2022 5:07:00 p. m.',
 '1/01/2022 5:10:00 p. m.',
 '1/01/2022 5:11:00 a. m.',
 '1/01/2022 5:14:00 p. m.',
 '1/01/2022 5:17:00 p. m.',
 '1/01/2022 5:20:00 p. m.',
 '1/01/2022 5:22:00 a. m.',
 '1/01/2022 5:23:00 a. m.',
 '1/01/2022 5:28:00 p. m.',
 '1/01/2022 5:30:00 a. m.',
 '1/01/2022 5:30:00 p. m.',
 '1/01/2022 5:35:00 a. m.',
 '1/01/2022 5:40:00 p. m.',
 '1/01/2022 5:50:00 a. m.',
 '1/01/2022 5:50:00 p. m.',
 '1/01/2022 5:52:00 a. m.',
 '1/01/2022 5:58:00 p. m.',
 '1/01/2022 6:00:00 a. m.',
 '1/01/2022 6:00:00 p. m.',
 '1/01/2022 6:01:00 p. m.',
 '1/01/2022 6:10:00 a. m.',
 '1/01/2022 6:10:00 p. m.',
 '1/01/2022 6:12:00 p. m.',
 '1/01/2022 6:20:00 a. m.',
 '1/01/2022 6:23:00 p. m.',
 '1/01/2022 6:28:00 p. m.',
 '1/01/2022 6:29:00 p. m.',
 '1/01/2022 6:30:00 p. m.',
 '1/01/2022 6:38:00 a. m.',
 '1/01/2022 6:38:00 p. m.',
 '1/01/2022 6:40:00 p. m.',
 '1/01/2022 6:41:00 p. m.',
 '1/01/2022 6:48:00 a. m.',
 '1/01/2022 6:50:00 p. m.',
 '1/01/2022 6:58:00 a. m.',
 '1/01/2022 6:59:00 a. m.',
 '1/01/2022 7:00:00 a. m.',
 '1/01/2022 7:00:00 p. m.',
 '1/01/2022 7:06:00 p. m.',
 '1/01/2022 7:08:00 a. m.',
 '1/01/2022 7:09:00 p. m.',
 '1/01/2022 7:15:00 p. m.',
 '1/01/2022 7:16:00 a. m.',
 '1/01/2022 7:16:00 p. m.',
 '1/01/2022 7:20:00 p. m.',
 '1/01/2022 7:24:00 p. m.',
 '1/01/2022 7:28:00 a. m.',
 '1/01/2022 7:30:00 p. m.',
 '1/01/2022 7:31:00 p. m.',
 '1/01/2022 7:32:00 a. m.',
 '1/01/2022 7:33:00 p. m.',
 '1/01/2022 7:37:00 a. m.',
 '1/01/2022 7:45:00 a. m.',
 '1/01/2022 7:47:00 p. m.',
 '1/01/2022 7:48:00 a. m.',
 '1/01/2022 7:50:00 a. m.',
 '1/01/2022 7:50:00 p. m.',
 '1/01/2022 7:52:00 a. m.',
 '1/01/2022 7:53:00 a. m.',
 '1/01/2022 7:56:00 a. m.',
 '1/01/2022 8:00:00 a. m.',
 '1/01/2022 8:00:00 p. m.',
 '1/01/2022 8:01:00 a. m.',
 '1/01/2022 8:03:00 a. m.',
 '1/01/2022 8:03:00 p. m.',
 '1/01/2022 8:06:00 a. m.',
 '1/01/2022 8:06:00 p. m.',
 '1/01/2022 8:10:00 a. m.',
 '1/01/2022 8:10:00 p. m.',
 '1/01/2022 8:14:00 p. m.',
 '1/01/2022 8:19:00 a. m.',
 '1/01/2022 8:20:00 a. m.',
 '1/01/2022 8:20:00 p. m.',
 '1/01/2022 8:21:00 p. m.',
 '1/01/2022 8:22:00 a. m.',
 '1/01/2022 8:29:00 p. m.',
 '1/01/2022 8:30:00 a. m.',
 '1/01/2022 8:30:00 p. m.',
 '1/01/2022 8:33:00 a. m.',
 '1/01/2022 8:34:00 a. m.',
 '1/01/2022 8:36:00 a. m.',
 '1/01/2022 8:37:00 a. m.',
 '1/01/2022 8:38:00 a. m.',
 '1/01/2022 8:40:00 a. m.',
 '1/01/2022 8:40:00 p. m.',
 '1/01/2022 8:49:00 p. m.',
 '1/01/2022 8:50:00 a. m.',
 '1/01/2022 8:50:00 p. m.',
 '1/01/2022 8:56:00 a. m.',
 '1/01/2022 9:00:00 p. m.',
 '1/01/2022 9:02:00 a. m.',
 '1/01/2022 9:06:00 a. m.',
 '1/01/2022 9:10:00 a. m.',
 '1/01/2022 9:10:00 p. m.',
 '1/01/2022 9:11:00 a. m.',
 '1/01/2022 9:15:00 a. m.',
 '1/01/2022 9:15:00 p. m.',
 '1/01/2022 9:16:00 a. m.',
 '1/01/2022 9:19:00 a. m.',
 '1/01/2022 9:21:00 p. m.',
 '1/01/2022 9:24:00 p. m.',
 '1/01/2022 9:25:00 a. m.',
 '1/01/2022 9:30:00 a. m.',
 '1/01/2022 9:30:00 p. m.',
 '1/01/2022 9:32:00 a. m.',
 '1/01/2022 9:36:00 a. m.',
 '1/01/2022 9:38:00 a. m.',
 '1/01/2022 9:40:00 a. m.',
 '1/01/2022 9:40:00 p. m.',
 '1/01/2022 9:41:00 a. m.',
 '1/01/2022 9:43:00 p. m.',
 '1/01/2022 9:47:00 a. m.',
 '1/01/2022 9:48:00 a. m.',
 '1/01/2022 9:50:00 a. m.',
 '1/01/2022 9:50:00 p. m.',
 '1/01/2022 9:53:00 a. m.',
 '1/01/2022 9:55:00 a. m.',
 '1/01/2022 9:57:00 a. m.',
 '1/01/2022 9:57:00 p. m.',
 '1/02/2021',
 '1/02/2021 10:00:00 a. m.',
 '1/02/2021 10:02:00 a. m.',
 '1/02/2021 10:02:00 p. m.',
 '1/02/2021 10:04:00 a. m.',
 '1/02/2021 10:05:00 a. m.',
 '1/02/2021 10:06:00 a. m.',
 '1/02/2021 10:07:00 a. m.',
 '1/02/2021 10:10:00 a. m.',
 '1/02/2021 10:10:00 p. m.',
 '1/02/2021 10:11:00 a. m.',
 '1/02/2021 10:13:00 a. m.',
 '1/02/2021 10:14:00 a. m.',
 '1/02/2021 10:17:00 a. m.',
 '1/02/2021 10:18:00 a. m.',
 '1/02/2021 10:19:00 a. m.',
 '1/02/2021 10:20:00 a. m.',
 '1/02/2021 10:20:00 p. m.',
 '1/02/2021 10:21:00 a. m.',
 '1/02/2021 10:21:00 p. m.',
 '1/02/2021 10:22:00 a. m.',
 '1/02/2021 10:23:00 a. m.',
 '1/02/2021 10:23:00 p. m.',
 '1/02/2021 10:24:00 a. m.',
 '1/02/2021 10:25:00 a. m.',
 '1/02/2021 10:26:00 a. m.',
 '1/02/2021 10:27:00 a. m.',
 '1/02/2021 10:28:00 a. m.',
 '1/02/2021 10:29:00 a. m.',
 '1/02/2021 10:29:00 p. m.',
 '1/02/2021 10:30:00 a. m.',
 '1/02/2021 10:30:00 p. m.',
 '1/02/2021 10:35:00 a. m.',
 '1/02/2021 10:37:00 a. m.',
 '1/02/2021 10:38:00 a. m.',
 '1/02/2021 10:40:00 a. m.',
 '1/02/2021 10:40:00 p. m.',
 '1/02/2021 10:42:00 a. m.',
 '1/02/2021 10:43:00 a. m.',
 '1/02/2021 10:44:00 a. m.',
 '1/02/2021 10:45:00 a. m.',
 '1/02/2021 10:46:00 a. m.',
 '1/02/2021 10:48:00 a. m.',

Despues de revisar la columna de fechas y de inspeccionar en la pagina del simit, resulta que son fechas y horas genericas, asi que para el caso no es información que represente una muestra real y se van a borrar de la tabla.

In [85]:
tabla = tabla.drop(columns=["fecha"])
tabla.head()

         departamento         ciudad placa_vehiculo codigo_infraccion
0                META  VILLAVICENCIO         UBW991               C03
1              CALDAS      MANIZALES         NAH651               C35
2  NORTE DE SANTANDER         CUCUTA      Conductor               D01
3              CALDAS      CHINCHINA         HVT31C               D01
4             BOLIVAR      CARTAGENA         FUP162               C02

In [86]:
tabla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1468847 entries, 0 to 1468846
Data columns (total 4 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   departamento       1468847 non-null  object
 1   ciudad             1468847 non-null  object
 2   placa_vehiculo     1468847 non-null  object
 3   codigo_infraccion  1468847 non-null  object
dtypes: object(4)
memory usage: 44.8+ MB

In [87]:
sorted(tabla["codigo_infraccion"].unique())

['107',
 '500',
 'A01',
 'A02',
 'A03',
 'A04',
 'A05',
 'A06',
 'A07',
 'A08',
 'A09',
 'A11',
 'A12',
 'B01',
 'B02',
 'B03',
 'B04',
 'B05',
 'B06',
 'B07',
 'B08',
 'B09',
 'B10',
 'B11',
 'B12',
 'B13',
 'B14',
 'B15',
 'B16',
 'B17',
 'B18',
 'B19',
 'B20',
 'B21',
 'B22',
 'B23',
 'C01',
 'C02',
 'C03',
 'C04',
 'C05',
 'C06',
 'C07',
 'C08',
 'C09',
 'C10',
 'C11',
 'C12',
 'C13',
 'C14',
 'C15',
 'C16',
 'C17',
 'C18',
 'C19',
 'C20',
 'C21',
 'C22',
 'C23',
 'C24',
 'C25',
 'C26',
 'C27',
 'C28',
 'C29',
 'C30',
 'C31',
 'C32',
 'C33',
 'C34',
 'C35',
 'C36',
 'C37',
 'C38',
 'C39',
 'C40',
 'D01',
 'D02',
 'D03',
 'D04',
 'D05',
 'D06',
 'D07',
 'D08',
 'D10',
 'D11',
 'D12',
 'D13',
 'D14',
 'D15',
 'D16',
 'D17',
 'E01',
 'E02',
 'E04',
 'F',
 'F01',
 'F02',
 'F04',
 'F06',
 'F07',
 'G01',
 'G02',
 'H01',
 'H02',
 'H03',
 'H04',
 'H05',
 'H06',
 'H07',
 'H08',
 'H09',
 'H10',
 'H12',
 'H13',
 'I01',
 'J01']

In [88]:
tabla["codigo_infraccion"] = tabla["codigo_infraccion"].str.strip()
Reemplazos_ciudades = {"107":"C29",# para el caso se ascosia con el articulo 107, exceso e velocidad
                       "500":"C35" # Para el caso y no descompletar datos se asume error de digitación y confusión con el articulo 50, vehiculo en mal estado
                       }
tabla["codigo_infraccion"] = tabla["codigo_infraccion"].replace(Reemplazos_ciudades)
sorted(tabla["codigo_infraccion"].unique())

['A01',
 'A02',
 'A03',
 'A04',
 'A05',
 'A06',
 'A07',
 'A08',
 'A09',
 'A11',
 'A12',
 'B01',
 'B02',
 'B03',
 'B04',
 'B05',
 'B06',
 'B07',
 'B08',
 'B09',
 'B10',
 'B11',
 'B12',
 'B13',
 'B14',
 'B15',
 'B16',
 'B17',
 'B18',
 'B19',
 'B20',
 'B21',
 'B22',
 'B23',
 'C01',
 'C02',
 'C03',
 'C04',
 'C05',
 'C06',
 'C07',
 'C08',
 'C09',
 'C10',
 'C11',
 'C12',
 'C13',
 'C14',
 'C15',
 'C16',
 'C17',
 'C18',
 'C19',
 'C20',
 'C21',
 'C22',
 'C23',
 'C24',
 'C25',
 'C26',
 'C27',
 'C28',
 'C29',
 'C30',
 'C31',
 'C32',
 'C33',
 'C34',
 'C35',
 'C36',
 'C37',
 'C38',
 'C39',
 'C40',
 'D01',
 'D02',
 'D03',
 'D04',
 'D05',
 'D06',
 'D07',
 'D08',
 'D10',
 'D11',
 'D12',
 'D13',
 'D14',
 'D15',
 'D16',
 'D17',
 'E01',
 'E02',
 'E04',
 'F',
 'F01',
 'F02',
 'F04',
 'F06',
 'F07',
 'G01',
 'G02',
 'H01',
 'H02',
 'H03',
 'H04',
 'H05',
 'H06',
 'H07',
 'H08',
 'H09',
 'H10',
 'H12',
 'H13',
 'I01',
 'J01']

In [90]:
tabla.head()

         departamento         ciudad placa_vehiculo codigo_infraccion
0                META  VILLAVICENCIO         UBW991               C03
1              CALDAS      MANIZALES         NAH651               C35
2  NORTE DE SANTANDER         CUCUTA      Conductor               D01
3              CALDAS      CHINCHINA         HVT31C               D01
4             BOLIVAR      CARTAGENA         FUP162               C02

# 3. Exportación csv

In [89]:
tabla.to_csv("Infracciones_Colombia.csv", index=False)